import { Theme } from "../theme/index.slint";

export component RDSSelectButton {
    in property <string> label;
    in property <bool> active;
    callback clicked();

    width: 80px;
    height: 28px;

    Rectangle {
        width: parent.width;
        height: parent.height;
        background: root.active ? Theme.active.accent_secondary : Theme.active.background_main;
        border-radius: Theme.active.radius_large;
        border-color: root.active ? Theme.active.accent_highlight : Theme.active.border_subtle;
        border-width: 1px;

        Text {
            text: root.label;
            color: Theme.active.text_primary;
            font-size: Theme.active.font_small;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        TouchArea {
            width: parent.width;
            height: parent.height;
            clicked => root.clicked();
        }
    }

}

export component RDSSequencerCell {
    in property <bool> active;
    in property <bool> current;
    callback clicked();

    width: 20px;
    height: 20px;

    Rectangle {
        width: parent.width;
        height: parent.height;
        background: root.current ? Theme.active.text_primary : (root.active ? Theme.active.accent_primary : Theme.active.border_subtle);
        border-radius: Theme.active.radius_small;
        border-color: Theme.active.border_strong;
        border-width: 1px;

        TouchArea {
            width: parent.width;
            height: parent.height;
            clicked => root.clicked();
        }
    }
}